# Generated by Django 2.0.3 on 2020-05-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='userID',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='siteactivitytype',
            old_name='siteActivityid',
            new_name='siteActivityId',
        ),
        migrations.RemoveField(
            model_name='site',
            name='id',
        ),
        migrations.AlterField(
            model_name='site',
            name='siteId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='siteName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
