# Generated by Django 2.0.3 on 2020-05-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20200513_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='siteName',
            field=models.CharField(max_length=1024),
        ),
    ]
